service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.getData
    events:
      - http:
          path: data
          method: get