service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: handler.getData
    events:
      - http:
          path: data
          method: get

  postData:
    handler: handler.postData
    events:
      - http:
          path: data
          method: post